# Generated by Django 3.0.7 on 2020-12-02 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_title', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DR', 'Deleware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=200)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Org. Contact Phone', max_length=31)),
                ('website_url', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('EL', 'Elementary School'), ('MD', 'Middle School'), ('HS', 'High School'), ('NP', 'Nonprofit'), ('CH', 'Church')], max_length=2)),
                ('logo_url', models.CharField(blank='True', default='https://www.resetyourbody.com/wp-content/uploads/COMPANY_LOGO/logo-default.png', max_length=200)),
                ('promo_code', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('logo_url', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('kids', 'K-5 Sites'), ('science', 'Science'), ('search', 'Search Engines'), ('general', 'General Scholarships'), ('foster', 'Foster Youth Scholarships'), ('immigrant', 'Immigrant Youth Scholarships'), ('afam', 'African American Scholarships'), ('asam', 'Asian-Pacific American Scholarships'), ('hiam', 'Hispanic American Scholarships'), ('ntam', 'Native American Scholarships'), ('lgbtq', 'LGBTQ+ Scholarships'), ('women', 'Women Scholarships'), ('favs', 'Favorites')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254, verbose_name='student Email Address')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='parent Email Address')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Administrator')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=2000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Student')),
            ],
        ),
        migrations.AddField(
            model_name='administrator',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Organization'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
