# Generated by Django 3.0.7 on 2020-11-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_organization_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='admin',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='student_name',
        ),
        migrations.AlterField(
            model_name='organization',
            name='promo_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
