# Generated by Django 3.0.8 on 2020-11-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201121_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
