# Generated by Django 3.0.8 on 2020-11-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('logo_url', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('kids', 'K-5 Sites')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(max_length=254, verbose_name='parent Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, verbose_name='student Email Address'),
        ),
        migrations.DeleteModel(
            name='FavSites',
        ),
    ]
