# Generated by Django 3.0.7 on 2020-11-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(max_length=254, verbose_name='parent Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, verbose_name='student Email Address'),
        ),
    ]
