# Generated by Django 3.0.8 on 2020-11-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201126_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site',
            new_name='site_name',
        ),
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('kids', 'K-5 Sites'), ('science', 'Science'), ('search', 'Search Engines'), ('general', 'General Scholarships'), ('foster', 'Foster Youth Scholarships'), ('immigrant', 'Immigrant Youth Scholarships'), ('afam', 'African American Scholarships'), ('asam', 'Asian-Pacific American Scholarships'), ('hiam', 'Hispanic American Scholarships'), ('ntam', 'Native American Scholarships'), ('lgbtq', 'LGBTQ+ Scholarships'), ('women', 'Women Scholarships')], max_length=100),
        ),
    ]
