# Generated by Django 3.0.8 on 2020-11-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201128_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_name',
            new_name='site',
        ),
    ]
